@extends('layouts.app')
@section('page-title', 'Registrar salida')
@php
    $submittedItems = old('items', [['inventory_item_id' => '', 'quantity' => '']]);
    $inventoryOptions = $inventoryItems->map(fn($inventoryItem) => ['id' => (string) $inventoryItem->id, 'name' => $inventoryItem->product->name, 'unit' => $inventoryItem->product->unit->name, 'identifier' => $inventoryItem->product->code ?: $inventoryItem->product->barcode, 'usableStock' => (string) ($inventoryItem->usable_stock ?? '0.000')])->values();
@endphp
@section('content')
<div class="page-heading"><div><nav aria-label="Ruta de navegación"><ol class="breadcrumb small mb-2">@if(Auth::user()->isAdmin())<li class="breadcrumb-item"><a href="{{ route('warehouses.index') }}">Almacenes</a></li>@else<li class="breadcrumb-item"><a href="{{ route('home') }}">Inicio</a></li>@endif<li class="breadcrumb-item">{{ $warehouse->name }}</li><li class="breadcrumb-item"><a href="{{ route('warehouses.outbounds.index', $warehouse) }}">Salidas</a></li><li class="breadcrumb-item active">Nueva</li></ol></nav><h2>Registrar salida</h2><p>Captura el motivo y los productos que saldrán del almacén.</p><span class="badge text-bg-light border"><i class="bi bi-building me-1"></i>Almacén: {{ $warehouse->name }}</span></div></div>
@if($inventoryItems->isEmpty())<div class="alert alert-warning"><i class="bi bi-exclamation-triangle me-2"></i>Debes configurar productos con existencia utilizable en el inventario principal antes de registrar una salida.</div>@endif
<form method="POST" action="{{ route('warehouses.outbounds.store', $warehouse) }}" data-outbound-form novalidate>@csrf
<section class="admin-card mb-4"><div class="admin-card-header"><h3 class="h6 fw-bold mb-0">Datos de la salida</h3></div><div class="p-4"><div class="row g-3"><div class="col-lg-5"><label for="reason" class="form-label">Motivo <span class="text-danger">*</span></label><select id="reason" name="reason" class="form-select @error('reason') is-invalid @enderror" required><option value="">Selecciona un motivo</option>@foreach($reasons as $reason)<option value="{{ $reason->value }}" @selected(old('reason') === $reason->value)>{{ $reason->label() }}</option>@endforeach</select>@error('reason')<div class="invalid-feedback">{{ $message }}</div>@enderror</div><div class="col-lg-7"><label for="notes" class="form-label">Comentario <span class="text-body-secondary fw-normal">(Opcional)</span></label><textarea id="notes" name="notes" rows="2" maxlength="2000" class="form-control @error('notes') is-invalid @enderror" placeholder="Agrega información adicional sobre la salida si es necesario.">{{ old('notes') }}</textarea>@error('notes')<div class="invalid-feedback">{{ $message }}</div>@enderror</div></div></div></section>
<section class="admin-card mb-4" data-outbound-items data-inventory-options='@json($inventoryOptions)'><div class="admin-card-header d-flex flex-wrap justify-content-between gap-2 align-items-center"><div><h3 class="h6 fw-bold mb-1">Productos a retirar</h3><p class="small text-body-secondary mb-0">El sistema seleccionará automáticamente los lotes disponibles, priorizando los que caduquen primero.</p></div><button type="button" class="btn btn-sm btn-outline-primary" data-add-outbound-item><i class="bi bi-plus-circle me-1"></i>Agregar producto</button></div><div class="p-3 p-lg-4">@error('items')<div class="alert alert-danger py-2">{{ $message }}</div>@enderror<div data-outbound-items-list>@foreach($submittedItems as $index => $submittedItem)@include('outbounds._item', ['index' => $index, 'item' => $submittedItem, 'inventoryItems' => $inventoryItems])@endforeach</div></div></section>
<div class="alert alert-light border small"><i class="bi bi-info-circle me-2"></i>Una vez registrada, la salida quedará como historial y no podrá editarse ni eliminarse desde este módulo.</div><div class="form-actions"><a href="{{ route('warehouses.outbounds.index', $warehouse) }}" class="btn btn-light border">Cancelar</a><button type="submit" class="btn btn-primary" data-outbound-submit @disabled($inventoryItems->isEmpty())><i class="bi bi-check-circle me-2"></i>Registrar salida</button></div></form>
<template data-outbound-item-template>@include('outbounds._item', ['index' => '__INDEX__', 'item' => [], 'inventoryItems' => $inventoryItems])</template>
@endsection
