@extends('layouts.app')
@section('page-title', 'Crear vale de Administración')
@section('content')
<h2>Crear vale de Administración</h2><p class="text-body-secondary">Solicita productos para reponer un gabinete.</p>
<form method="POST" action="{{ route('administration-vouchers.store') }}" class="card card-body border-0 shadow-sm" id="administration-voucher-form">@csrf
<div class="row g-3"><div class="col-md-6"><label class="form-label">Almacén</label><select name="warehouse_id" id="admin-warehouse" class="form-select @error('warehouse_id') is-invalid @enderror" required><option value="">Selecciona un almacén</option>@foreach($warehouses as $warehouse)<option value="{{ $warehouse->id }}" @selected((string)old('warehouse_id')===(string)$warehouse->id)>{{ $warehouse->name }}</option>@endforeach</select>@error('warehouse_id')<div class="invalid-feedback">{{ $message }}</div>@enderror</div><div class="col-md-6"><label class="form-label">Gabinete</label><select name="cabinet_id" id="admin-cabinet" class="form-select @error('cabinet_id') is-invalid @enderror" required><option value="">Selecciona un gabinete</option></select>@error('cabinet_id')<div class="invalid-feedback">{{ $message }}</div>@enderror</div></div>
<hr><div class="d-flex justify-content-between"><h3 class="h5">Productos</h3><button type="button" class="btn btn-outline-primary btn-sm" id="add-admin-item">Agregar producto</button></div><div id="admin-items" class="d-grid gap-3 mt-3"></div>@error('items')<div class="text-danger small">{{ $message }}</div>@enderror
<div class="mt-3"><label class="form-label">Notas <span class="text-body-secondary">(Opcional)</span></label><textarea name="notes" class="form-control">{{ old('notes') }}</textarea></div><div class="mt-4 d-flex gap-2"><a href="{{ route('administration-vouchers.index') }}" class="btn btn-outline-secondary">Cancelar</a><button class="btn btn-primary">Crear vale</button></div></form>
@php($catalog = $warehouses->mapWithKeys(fn($w)=>[$w->id=>['cabinets'=>$w->cabinets->map(fn($c)=>['id'=>$c->id,'name'=>$c->name,'products'=>$c->inventoryItems->filter(fn($ci)=>$w->inventoryItems->contains('product_id',$ci->product_id))->map(fn($ci)=>['id'=>$ci->product->id,'name'=>$ci->product->name,'unit'=>$ci->product->unit->name])->values()])->values()]]))
<script>document.addEventListener('DOMContentLoaded',()=>{const data=@json($catalog),w=document.querySelector('#admin-warehouse'),c=document.querySelector('#admin-cabinet'),box=document.querySelector('#admin-items'),oldCab=@json(old('cabinet_id')),oldItems=@json(old('items',[['product_id'=>'','quantity'=>'']]));let rows=oldItems;function cabinets(){c.innerHTML='<option value="">Selecciona un gabinete</option>';Object.values(data[w.value]?.cabinets||{}).forEach(x=>c.add(new Option(x.name,x.id,false,String(x.id)===String(oldCab))));render()}function products(){return Object.values(data[w.value]?.cabinets||{}).find(x=>String(x.id)===String(c.value))?.products||[]}function render(){box.innerHTML='';rows.forEach((r,i)=>{let d=document.createElement('div');d.className='row g-2 align-items-end border rounded p-2';d.innerHTML=`<div class="col-md-7"><label class="form-label">Producto</label><select class="form-select" name="items[${i}][product_id]" required><option value="">Selecciona un producto</option>${products().map(p=>`<option value="${p.id}" ${String(p.id)===String(r.product_id)?'selected':''}>${p.name} — ${p.unit}</option>`).join('')}</select></div><div class="col-md-3"><label class="form-label">Cantidad</label><input class="form-control" type="number" step="0.001" min="0.001" name="items[${i}][quantity]" value="${r.quantity||''}" required></div><div class="col-md-2"><button type="button" class="btn btn-outline-danger w-100">Quitar</button></div>`;d.querySelector('button').onclick=()=>{if(rows.length>1){rows.splice(i,1);render()}};box.append(d)})}w.onchange=()=>{cabinets()};c.onchange=render;document.querySelector('#add-admin-item').onclick=()=>{rows.push({product_id:'',quantity:''});render()};cabinets();});</script>
@endsection
