@extends('layouts.app')
@section('page-title', 'Vale de Administración #'.$voucher->id)
@section('content')
<div class="d-flex justify-content-between mb-4"><div><h2>Vale de Administración #{{ $voucher->id }}</h2><span class="badge {{ $voucher->status->badgeClass() }}">{{ $voucher->status->label() }}</span></div><a href="{{ route('administration-vouchers.index') }}" class="btn btn-outline-secondary">Volver</a></div>
<div class="card card-body border-0 shadow-sm mb-4"><div class="row g-3"><div class="col-md-3"><small>Almacén</small><strong class="d-block">{{ $voucher->warehouse->name }}</strong></div><div class="col-md-3"><small>Gabinete</small><strong class="d-block">{{ $voucher->cabinet->name }}</strong></div><div class="col-md-3"><small>Solicitó</small><strong class="d-block">{{ $voucher->requester->name }} {{ $voucher->requester->last_name_one }}</strong></div><div class="col-md-3"><small>Fecha</small><strong class="d-block">{{ $voucher->requested_at->format('d/m/Y H:i') }}</strong></div><div class="col-12"><small>Notas</small><p class="mb-0">{{ $voucher->notes ?: 'Sin notas' }}</p></div>@if($voucher->rejection_reason)<div class="col-12"><small>Motivo del rechazo</small><p>{{ $voucher->rejection_reason }}</p></div>@endif</div></div>
<div class="card border-0 shadow-sm mb-4"><div class="table-responsive"><table class="table mb-0"><thead><tr><th>Producto</th><th>Solicitado</th><th>Surtido</th><th>Pendiente</th><th>Unidad</th></tr></thead><tbody>@foreach($voucher->items as $item)<tr><td>{{ $item->product->name }}</td><td>{{ rtrim(rtrim($item->requested_quantity,'0'),'.') }}</td><td>{{ rtrim(rtrim($item->supplied_quantity,'0'),'.') }}</td><td class="fw-bold">{{ rtrim(rtrim($item->pendingQuantity(),'0'),'.') }}</td><td>{{ $item->product->unit->name }}</td></tr>@endforeach</tbody></table></div></div>
@can('fulfill',$voucher) @if(in_array($voucher->status,[\App\Enums\AdministrationVoucherStatus::PENDING,\App\Enums\AdministrationVoucherStatus::PARTIALLY_SUPPLIED],true))
<section class="card card-body border-0 shadow-sm mb-4"><h3 class="h5">Surtir vale</h3><form method="POST" action="{{ route('administration-vouchers.fulfillments.store',$voucher) }}">@csrf @foreach($voucher->items as $i=>$item) @if(bccomp($item->pendingQuantity(),'0',3)>0)<div class="row g-2 align-items-end border-bottom py-3"><div class="col-md-5"><strong>{{ $item->product->name }}</strong><div class="small text-body-secondary">Solicitado: {{ $item->requested_quantity }} · Surtido: {{ $item->supplied_quantity }} · Pendiente: {{ $item->pendingQuantity() }}</div><div class="small">Disponible: {{ $inventoryItems->get($item->product_id)?->usable_stock ?? '0.000' }}</div></div><input type="hidden" name="items[{{ $i }}][voucher_item_id]" value="{{ $item->id }}"><div class="col-md-4"><label class="form-label">Cantidad a surtir</label><input type="number" step="0.001" min="0" value="{{ old("items.$i.quantity",0) }}" name="items[{{ $i }}][quantity]" class="form-control"></div></div>@endif @endforeach<div class="mt-3"><label class="form-label">Notas (Opcional)</label><textarea name="notes" class="form-control">{{ old('notes') }}</textarea></div><button class="btn btn-primary mt-3">Registrar reposición</button></form></section>
@endif @endcan
@if($voucher->status===\App\Enums\AdministrationVoucherStatus::PENDING)<div class="d-flex gap-2 mb-4">@can('reject',$voucher)<form method="POST" action="{{ route('administration-vouchers.reject',$voucher) }}" class="d-flex gap-2">@csrf<input name="rejection_reason" class="form-control" required placeholder="Motivo del rechazo"><button class="btn btn-outline-danger">Rechazar vale</button></form>@endcan @can('cancel',$voucher)<form method="POST" action="{{ route('administration-vouchers.cancel',$voucher) }}">@csrf<button class="btn btn-outline-secondary">Cancelar vale</button></form>@endcan</div>@endif
<section><h3 class="h5">Historial de reposiciones</h3>@forelse($voucher->transfers as $transfer)<div class="card card-body border-0 shadow-sm mb-3"><div class="d-flex justify-content-between"><div><strong>Transferencia #{{ $transfer->id }}</strong><div>{{ $transfer->transferred_at->format('d/m/Y H:i') }} · {{ $transfer->transferredBy->name }}</div></div><a href="{{ route('warehouses.transfers.show',[$voucher->warehouse,$transfer]) }}" class="btn btn-sm btn-outline-primary">Ver transferencia</a></div><ul class="mt-3 mb-0">@foreach($transfer->items as $item)<li>{{ $item->sourceInventoryItem->product->name }}: {{ $item->requested_quantity }} @foreach($item->allocations as $allocation)<small class="d-block">Lote {{ $allocation->sourceBatch->internal_lot }} → {{ $allocation->destinationBatch->internal_lot }}: {{ $allocation->quantity }}</small>@endforeach</li>@endforeach</ul></div>@empty<p class="text-body-secondary">Aún no hay reposiciones registradas.</p>@endforelse</section>
@endsection
