@extends('layouts.app')
@php
$isCabinet = $cabinet instanceof \App\Models\Cabinet;
$params = $isCabinet ? [$warehouse, $cabinet, $inventoryItem] : [$warehouse, $inventoryItem];
$prefix = $isCabinet ? 'warehouses.cabinets.inventory.adjustments' : 'warehouses.inventory.adjustments';
@endphp
@section('page-title', 'Registrar ajuste')
@section('content')
<div class="page-heading"><div><nav aria-label="Ruta de navegación"><ol class="breadcrumb small mb-2"><li class="breadcrumb-item"><a href="{{ Auth::user()->isAdmin() ? route('warehouses.index') : route('home') }}">{{ Auth::user()->isAdmin() ? 'Almacenes' : 'Inicio' }}</a></li><li class="breadcrumb-item">{{ $warehouse->name }}</li>@if($isCabinet)<li class="breadcrumb-item">{{ $cabinet->name }}</li>@endif<li class="breadcrumb-item"><a href="{{ route($prefix.'.index', $params) }}">Ajustes</a></li><li class="breadcrumb-item active">Registrar</li></ol></nav><h2>Registrar ajuste</h2><p>Corrige la existencia registrada a partir de un conteo físico.</p><div class="d-flex flex-wrap gap-2"><span class="badge text-bg-light border">Producto: {{ $inventoryItem->product->name }}</span><span class="badge text-bg-light border">Unidad: {{ $inventoryItem->product->unit->name }}</span><span class="badge text-bg-light border">Almacén: {{ $warehouse->name }}</span>@if($isCabinet)<span class="badge text-bg-light border">Gabinete: {{ $cabinet->name }}</span>@endif</div></div></div>
<div class="alert alert-info border-0 shadow-sm"><i class="bi bi-info-circle-fill me-2"></i>Selecciona el lote que fue contado físicamente e indica la cantidad encontrada. El sistema calculará automáticamente la diferencia.</div>
@if($batches->isEmpty())
<section class="admin-card"><div class="empty-state"><span class="empty-state-icon"><i class="bi bi-box-seam"></i></span><h3 class="h5">Este producto todavía no tiene lotes que puedan ajustarse.</h3><p class="text-body-secondary">La existencia inicial debe registrarse mediante una entrada.</p><a href="{{ route($prefix.'.index', $params) }}" class="btn btn-light border">Volver a ajustes</a></div></section>
@else
<form method="POST" action="{{ route($prefix.'.store', $params) }}" class="admin-card mx-auto" style="max-width:860px" data-adjustment-form data-adjustment-batches='@json($batchOptions)'>@csrf
<div class="admin-card-header"><h3 class="h6 fw-bold mb-0">Datos del conteo</h3></div><div class="p-3 p-md-4">
<div class="mb-4"><label for="inventory_batch_id" class="form-label">Lote</label><select id="inventory_batch_id" name="inventory_batch_id" class="form-select @error('inventory_batch_id') is-invalid @enderror" required data-adjustment-batch><option value="">Selecciona un lote</option>@foreach($batches as $batch)<option value="{{ $batch->id }}" @selected((string)old('inventory_batch_id') === (string)$batch->id)>{{ $batch->internal_lot }} — Fabricante: {{ $batch->manufacturer_lot ?: 'No indicado' }} — Existencia: {{ \App\Models\InventoryItem::formatQuantity($batch->available_quantity) }}{{ $batch->expiration_date ? ' — Caduca: '.$batch->expiration_date->format('d/m/Y') : ' — Sin caducidad' }}</option>@endforeach</select>@error('inventory_batch_id')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
<div class="rounded border bg-body-tertiary p-3 mb-4" aria-live="polite"><div class="row g-3"><div class="col-sm-4"><span class="small text-body-secondary d-block">Existencia registrada</span><strong data-adjustment-current>—</strong> {{ $inventoryItem->product->unit->name }}</div><div class="col-sm-4"><span class="small text-body-secondary d-block">Lote fabricante</span><strong data-adjustment-manufacturer>—</strong></div><div class="col-sm-4"><span class="small text-body-secondary d-block">Caducidad</span><strong data-adjustment-expiration>—</strong> <span class="badge text-bg-danger d-none" data-adjustment-expired>Vencido</span></div></div></div>
<div class="row g-3 mb-4"><div class="col-md-6"><label for="counted_quantity" class="form-label">Cantidad contada</label><input id="counted_quantity" name="counted_quantity" type="number" step="0.001" min="0" value="{{ old('counted_quantity') }}" class="form-control @error('counted_quantity') is-invalid @enderror" required data-adjustment-counted>@error('counted_quantity')<div class="invalid-feedback">{{ $message }}</div>@enderror</div><div class="col-md-6"><span class="form-label d-block">Diferencia</span><span class="badge text-bg-secondary fs-5" data-adjustment-difference>—</span><div class="small text-warning-emphasis mt-2 d-none" data-adjustment-equal>La cantidad contada coincide con la existencia registrada.</div></div></div>
<div class="mb-4"><label for="reason" class="form-label">Motivo</label><select id="reason" name="reason" class="form-select @error('reason') is-invalid @enderror" required><option value="">Selecciona un motivo</option>@foreach($reasons as $reason)<option value="{{ $reason->value }}" @selected(old('reason') === $reason->value)>{{ $reason->label() }}</option>@endforeach</select>@error('reason')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
<div class="mb-4"><label for="notes" class="form-label">Comentario</label><textarea id="notes" name="notes" rows="3" maxlength="2000" placeholder="Agrega información adicional sobre el ajuste si es necesario." class="form-control @error('notes') is-invalid @enderror">{{ old('notes') }}</textarea><div class="form-text">Opcional</div>@error('notes')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
<div class="alert alert-light border small"><i class="bi bi-clock-history me-1"></i>Una vez registrado, el ajuste quedará en el historial y no podrá editarse ni eliminarse.</div><div class="d-flex flex-column-reverse flex-sm-row justify-content-end gap-2"><a href="{{ route($prefix.'.index', $params) }}" class="btn btn-light border">Cancelar</a><button type="submit" class="btn btn-primary" data-adjustment-submit disabled>Registrar ajuste</button></div>
</div></form>
@endif
@endsection
