@extends('layouts.app')
@php
$isCabinet = $cabinet instanceof \App\Models\Cabinet;
$params = $isCabinet ? [$warehouse, $cabinet, $inventoryItem] : [$warehouse, $inventoryItem];
$prefix = $isCabinet ? 'warehouses.cabinets.inventory.adjustments' : 'warehouses.inventory.adjustments';
$kardexRoute = route($isCabinet ? 'warehouses.cabinets.kardex.index' : 'warehouses.kardex.index', array_merge($isCabinet ? [$warehouse, $cabinet] : [$warehouse], ['inventory_item_id' => $inventoryItem->id]));
$positive = bccomp($adjustment->difference, '0', 3) > 0;
@endphp
@section('page-title', 'Detalle de ajuste')
@section('content')
<div class="page-heading"><div><nav aria-label="Ruta de navegación"><ol class="breadcrumb small mb-2"><li class="breadcrumb-item"><a href="{{ Auth::user()->isAdmin() ? route('warehouses.index') : route('home') }}">{{ Auth::user()->isAdmin() ? 'Almacenes' : 'Inicio' }}</a></li><li class="breadcrumb-item">{{ $warehouse->name }}</li>@if($isCabinet)<li class="breadcrumb-item">{{ $cabinet->name }}</li>@endif<li class="breadcrumb-item"><a href="{{ route($prefix.'.index', $params) }}">Ajustes</a></li><li class="breadcrumb-item active">Detalle</li></ol></nav><h2>Detalle de ajuste</h2><p>Consulta la corrección histórica realizada sobre el lote.</p></div><div class="d-flex gap-2 flex-wrap"><a href="{{ $kardexRoute }}" class="btn btn-light border">Ver Kardex</a><a href="{{ route($prefix.'.index', $params) }}" class="btn btn-primary">Volver a ajustes</a></div></div>
<section class="admin-card mx-auto" style="max-width:960px"><div class="admin-card-header"><h3 class="h6 fw-bold mb-0">Información del ajuste</h3></div><div class="p-3 p-md-4">
<div class="row g-4"><div class="col-md-6"><dl class="row mb-0"><dt class="col-5">Almacén</dt><dd class="col-7">{{ $warehouse->name }}</dd>@if($isCabinet)<dt class="col-5">Gabinete</dt><dd class="col-7">{{ $cabinet->name }}</dd>@endif<dt class="col-5">Producto</dt><dd class="col-7">{{ $inventoryItem->product->name }}</dd><dt class="col-5">Unidad</dt><dd class="col-7">{{ $inventoryItem->product->unit->name }}</dd><dt class="col-5">Motivo</dt><dd class="col-7">{{ $adjustment->reason->label() }}</dd></dl></div><div class="col-md-6"><dl class="row mb-0"><dt class="col-5">Lote interno</dt><dd class="col-7">{{ $adjustment->inventoryBatch->internal_lot }}</dd><dt class="col-5">Lote fabricante</dt><dd class="col-7">{{ $adjustment->inventoryBatch->manufacturer_lot ?: 'No indicado' }}</dd><dt class="col-5">Caducidad</dt><dd class="col-7">{{ $adjustment->inventoryBatch->expiration_date?->format('d/m/Y') ?? 'Sin caducidad' }}</dd><dt class="col-5">Realizó</dt><dd class="col-7">{{ $adjustment->adjustedBy->name }}</dd><dt class="col-5">Fecha y hora</dt><dd class="col-7">{{ $adjustment->adjusted_at->format('d/m/Y H:i') }}</dd></dl></div></div><hr class="my-4">
<div class="row g-3 text-center"><div class="col-sm-4"><div class="rounded border p-3"><span class="small text-body-secondary d-block">Cantidad anterior</span><strong class="fs-4">{{ \App\Models\InventoryItem::formatQuantity($adjustment->previous_quantity) }}</strong></div></div><div class="col-sm-4"><div class="rounded border p-3"><span class="small text-body-secondary d-block">Cantidad contada</span><strong class="fs-4">{{ \App\Models\InventoryItem::formatQuantity($adjustment->counted_quantity) }}</strong></div></div><div class="col-sm-4"><div class="rounded border p-3"><span class="small text-body-secondary d-block">Diferencia</span><span class="badge fs-5 {{ $positive ? 'text-bg-success' : 'text-bg-danger' }}">{{ $positive ? '+' : '' }}{{ \App\Models\InventoryItem::formatQuantity($adjustment->difference) }}</span><span class="small d-block mt-1">{{ $positive ? 'Aumento de existencia' : 'Disminución de existencia' }}</span></div></div></div>
<div class="mt-4"><h3 class="h6">Comentario</h3><p class="mb-0 text-body-secondary">{{ $adjustment->notes ?: 'Sin comentario' }}</p></div>
</div></section>
@endsection
